### ISSUE TITLE
Content-Type is always text/html; charset=utf-8 ?

### ISSUE THREAD

**Issue by caub** [pillarjs/finalhandler#11]
I didn't encounter a bug, but I find https://github.com/pillarjs/finalhandler/blob/master/index.js#L205 strange, because content-Type is always set to text/html, for any file served, is it normal?

**Comment by dougwilson** [comment]
Yea, because the Content-Type relates to what is sent, and this module will send back the error HTML encoded, if necessary. On the develop branch I'm working on more error output types as well.

**Comment by caub** [comment]
Oh sorry, I misread https://github.com/expressjs/serve-static#serve-files-with-vanilla-nodejs-http-server this is the 3rd argument, finalHandler for errors, ok
