### ISSUE TITLE
Unable to resolve 'debug'

### ISSUE THREAD

**Issue by hhsnopek** [pillarjs/finalhandler#19]
Hey, I just updated express to the latest version `4.15.4` and it appears that finalhandler is unable to resolve debug. I took a look at a couple other projects that also had this issue (https://github.com/sendgrid/sendgrid-nodejs/issues/292 & https://github.com/html-next/flexi/issues/47) and you've added `debug` to dependencies in the `package.json`, so I'm unsure what's going on here.

## Details
```
$ node -v
v6.11.2
$ npm -v
3.10.10
```

### Error
```
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/node_modules/finalhandler/index.js:14:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

### Attempted resolutions
- remove and reinstall all `node_modules`
- remove/reinstall after cache clear (`rm -rf node_modules && npm cache clear && npm install`)
- downgrade to `express@4.15.3`
- use node 8.3, remove/reinstall all after cache clear

**Comment by dougwilson** [comment]
Hi @hhsnopek I'm not sure what would be the issue besides maybe something buggy on that machine or something. Have you tried any other machine to rule that out? I tried to reproduce with the same versions you listed without success. Here is a copy of my console when trying to reproduce the issue, if you can see something I did differently than you:
```
~
$ cd Code

~/Code
$ mkdir test-express

~/Code
$ cd test-express

~/Code/test-express
$ rm -rf node_modules

~/Code/test-express
$ npm cache clean

~/Code/test-express
$ node -v
v6.11.2

~/Code/test-express
$ npm -v
3.10.10

~/Code/test-express
$ npm i express
~/Code/test-express
`-- express@4.15.4
  +-- accepts@1.3.3
  | +-- mime-types@2.1.16
  | | `-- mime-db@1.29.0
  | `-- negotiator@0.6.1
  +-- array-flatten@1.1.1
  +-- content-disposition@0.5.2
  +-- content-type@1.0.2
  +-- cookie@0.3.1
  +-- cookie-signature@1.0.6
  +-- debug@2.6.8
  | `-- ms@2.0.0
  +-- depd@1.1.1
  +-- encodeurl@1.0.1
  +-- escape-html@1.0.3
  +-- etag@1.8.0
  +-- finalhandler@1.0.4
  | `-- unpipe@1.0.0
  +-- fresh@0.5.0
  +-- merge-descriptors@1.0.1
  +-- methods@1.1.2
  +-- on-finished@2.3.0
  | `-- ee-first@1.1.1
  +-- parseurl@1.3.1
  +-- path-to-regexp@0.1.7
  +-- proxy-addr@1.1.5
  | +-- forwarded@0.1.0
  | `-- ipaddr.js@1.4.0
  +-- qs@6.5.0
  +-- range-parser@1.2.0
  +-- send@0.15.4
  | +-- destroy@1.0.4
  | +-- http-errors@1.6.2
  | | `-- inherits@2.0.3
  | `-- mime@1.3.4
  +-- serve-static@1.12.4
  +-- setprototypeof@1.0.3
  +-- statuses@1.3.1
  +-- type-is@1.6.15
  | `-- media-typer@0.3.0
  +-- utils-merge@1.0.0
  `-- vary@1.1.1

~/Code/test-express
$ node -e 'require("express")().listen(3000, function(){console.log("app started on 3000")})'
app started on 3000
```

**Comment by dougwilson** [comment]
I did just notice you wrote `npm cache clear`, but `clear` is not a command that exists. If that is what you actually ran, perhaps try `npm cache clean` instead incase the root of this is a corrupted npm cache.

**Comment by hhsnopek** [comment]
@dougwilson The issue was actually in my build process, I was removing `src` from all `node_modules` which removed `debug` in this case. Thank you for your time and assistance!
