### ISSUE TITLE
Debug package not found

### ISSUE THREAD

**Issue by gupta-abhi** [pillarjs/finalhandler#23]
Hi Team,

We are deploying our web application on Heroku servers and are getting this error in the logs:

![image](https://user-images.githubusercontent.com/23701772/42079900-9fc16896-7b9e-11e8-8ea3-818db8aed9c8.png)

The error states that the index.js file is missing DEBUG package, but when we checked the build logs, we found that the package was successfully installed in the node_modules folder.

Kindly have a look at this.

Kind Regards,
Abhishek Gupta

**Comment by dougwilson** [comment]
Hi @hhsnopek I'm not sure what would be the issue besides maybe something buggy on that machine or something. Have you tried any other machine to rule that out? I tried to reproduce without success, but you never provided any instructions for how I can reproduce the issue, so I just tried the basic steps. Here is a copy of my console when trying to reproduce the issue, if you can see something I did differently than you:
```
~
$ cd Code

~/Code
$ mkdir test-express

~/Code
$ cd test-finalhandler

~/Code/test-finalhandler
$ rm -rf node_modules

~/Code/test-finalhandler
$ npm cache clean -f

~/Code/test-finalhandler
$ node -v
v8.11.3


~/Code/test-finalhandler
$ npm install finalhandler
~/Code/test-finalhandler
`-- finalhandler@1.1.1
  +-- debug@2.6.9
  | `-- ms@2.0.0
  +-- encodeurl@1.0.2
  +-- escape-html@1.0.3
  +-- on-finished@2.3.0
  | `-- ee-first@1.1.1
  +-- parseurl@1.3.2
  +-- statuses@1.4.0
  `-- unpipe@1.0.0

~/Code/test-express
$ node -pe 'require("finalhandler"); "OK"'
OK
```


Please provide complete versions of everything used, complete code to reproduce and complete steps, ideally in the format like I did above, where it provide the exact step-by-step commands to reproduce the issue. Thanks!

**Comment by hhsnopek** [comment]
@dougwilson I believe you meant to ping @gupta-abhi here 😄

**Comment by dougwilson** [comment]
Oops! Sorry, I was copying the format from your issue and forgot to change the at mention.

**Comment by dougwilson** [comment]
Closing due to no response from OP.
