### ISSUE TITLE
Please release a patch for this issue

### ISSUE THREAD

**Issue by ansidev** [pillarjs/finalhandler#28]
FYI:
https://www.npmjs.com/advisories/836

**Comment by dougwilson** [comment]
The advisory is in error.

**Comment by dougwilson** [comment]
@ronperris

**Comment by dougwilson** [comment]
The linked HackerOne report says:

> Severity | None (0.0)

**Comment by dougwilson** [comment]
I marked this as duplicate, so the conversation can be centralized here: https://github.com/pillarjs/finalhandler/issues/26#issuecomment-489229392
