### ISSUE TITLE
Your package is causing vulnerability

### ISSUE THREAD

**Issue by mhsalves** [pillarjs/finalhandler#29]
Some repos which use your dependency are vulnerable. 

For example:
![image](https://user-images.githubusercontent.com/30807170/57165025-f3eda980-6dc3-11e9-994f-a76e1306d66f.png)

Can you fix ?

**Comment by dougwilson** [comment]
So the listing is incorrect; the linked HackerOne classifies the severity as `none`, as there is no issue here.

@ronperris

**Comment by mhsalves** [comment]
https://github.com/pillarjs/finalhandler/issues/26
