### ISSUE TITLE
Also read status from err.statusCode

### ISSUE THREAD

**Issue by dougwilson** [pillarjs/finalhandler#3]
This module should also read the status from the error object by looking in `err.statusCode` per https://github.com/andrewrk/node-multiparty/issues/97

**Comment by moll** [comment]
While you're at it, @dougwilson, throw in `statusMessage` as well, would you? That's human readable and I've found it very useful to set it to a clearer name (e.g. `412 Bad CSRF Token` over `412 Precondition Failed`). Thanks!

In that vein, check out [StandardHttpError.js](https://github.com/moll/js-standard-http-error). An alternative to your http-errors library's approach. :-)

**Comment by dougwilson** [comment]
While you're where, @moll , if you haven't yet, can you take a look at [the upcoming 1.0 readme](https://github.com/pillarjs/finalhandler/tree/1.x#finalhandler) and see if the new options help at all in this regard?

**Comment by dougwilson** [comment]
And as a second P.S., are you thinking that perhaps this module lifts the `statusMessage` onto the HTTP protocol line for Node.js 0.12? http://nodejs.org/api/http.html#http_response_statusmessage

**Comment by moll** [comment]
The `message` option, that's for the body, right? Hehe, talk about an overloaded term. I was indeed thinking of `res.statusMessage`. I've been using Node v0.11 for so long that I didn't realize it was never available in Node v0.10.

If FinalHandler's talking about the response body, perhaps name the option so too? Or what was your line of reasoning for calling it `message`?

**Comment by dougwilson** [comment]
> I was indeed thinking of res.statusMessage

Ok :) Yes, I can definitely do this, then ! I can also get it to work on 0.8 and 0.10, just 0.12 makes it super easy without hacks :)

> Or what was your line of reasoning for calling it message? 

I don't have any particular reason :) I love hearing this feedback, though :)

**Comment by moll** [comment]
> > Or what was your line of reasoning for calling it message?
>
> I don't have any particular reason :) I love hearing this feedback, though :)

There you go. I propose `body` would be a more suitable term in the contex of HTTP responses. :-)

Though, as a side note, should I want to do more computation for the body, I'd probably just add a [simple middleware function](https://github.com/moll/js-standard-http-error#using-with-express). I've had something like that since the beginning.
