### ISSUE TITLE
npm security vulnerability

### ISSUE THREAD

**Issue by XhmikosR** [pillarjs/finalhandler#31]
As reported [here](https://github.com/karma-runner/karma/issues/3304):

```
cd my-app
npm i karma
npm audit
```

```
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Insecure Default Configuration                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ finalhandler                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ karma                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ karma > connect > finalhandler                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/836                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 low severity vulnerability in 2518 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```

**Comment by dougwilson** [comment]
I marked this as duplicate, so the conversation can be centralized here: https://github.com/pillarjs/finalhandler/issues/26#issuecomment-489229392

**Comment by XhmikosR** [comment]
NP, I didn't see anything relevant in the open issues. Maybe you should reopen #26 until a new version with the fix is published.

**Comment by dougwilson** [comment]
Publishing a new version won't resolve anything, as npm has set the affected version to all and so all new published versions will still be marked vulnerable. On top if that, it is unclear on what the issue is that should be fixed, as described in that issue.

The issue was closed when the change was merged and the open button is disabled.

**Comment by XhmikosR** [comment]
The problem as far as I understand it is the CSP change patch, but a new version hasn't been released with the fix.

Admittedly, this hasn't been handled properly by whoever gets the npm reports out...

**Comment by dougwilson** [comment]
That was what I thought, but if that were the case the old versions of the module would not be marked as vulnerable as well. Since releasing a new version will still be marked as vulnerable anyway, I'm waiting to hear from them so I can definitely cut one that they will mark as not vulnerable.

**Comment by XhmikosR** [comment]
All applies to all current versions not to future releases, as far as I understand it.

If you release a new version with the fix, ideally it should be only a patch release, then the people who review these things will mark the ones as vulnerable.

Again, this is how I get the whole situation myself. Personally, I would release a patch version with just this fix.

**Comment by dougwilson** [comment]
So if you're just going to argue here, I can't help you if you don't believe me.
