### ISSUE TITLE
req.socket.destroy is not a function

### ISSUE THREAD

**Issue by bernardwolff** [pillarjs/finalhandler#39]
We're occasionally seeing this error in our logs. Since the stack trace starts from node:internal, it's very hard to tell where it's coming from. It's unclear how to reproduce this issue since it only periodically happens. Can you give any hints on how to track down what is causing this? We're using express@4.17.1

```
TypeError: req.socket.destroy is not a function
    at Immediate.<anonymous> (/app/node_modules/finalhandler/index.js:36:10)
    at Immediate.<anonymous> (/app/node_modules/express/lib/router/index.js:36:10)
    at processImmediate (node:internal/timers:36:10)
    at process.topLevelDomainCallback (node:domain:36:10)
    at process.callbackTrampoline (node:internal/async_hooks:36:24)
```

**Comment by dougwilson** [comment]
Hi @bernardwolff sorry you are having that issue. It may help if you included the version of Node.js you are using as well. Unfortunately it is likely almost impossible to narrow down without a way to reproduce it, at least for me. If I were in your shoes, I would take a core dump when that happens to examine the objects at the time it occurred.

It would be strange that the `IncomingMessage` object has a `.socket` property that is missing a `.destroy` function, as the Node.js Socket object has always had one for all of Node.js's existence. My only off-hand guess is something you have set up may perhaps be fiddling with these objects in some way?

**Comment by dougwilson** [comment]
Closing due to no response.
