### ISSUE TITLE
Is `res._header` reliable?

### ISSUE THREAD

**Issue by JexCheng** [pillarjs/finalhandler#5]
I see [L92](https://github.com/pillarjs/finalhandler/blob/master/index.js#L92) used `res._header`, how does it differ from [response.headersSent](https://nodejs.org/api/http.html#http_response_headerssent) ? In my mind property names start with underscore is not public. I can't find any document about `response._header`.

**Comment by dougwilson** [comment]
It's truthy ness has the same meaning, but this module supports Node.js versions before res.headersSent existed, so cannot use that.
