### ISSUE TITLE
allow uncaught errors to bubble

### ISSUE THREAD

**Issue by ericuldall** [pillarjs/finalhandler#6]
Is there a way to allow unhandled errors to bubble up?

**Comment by dougwilson** [comment]
Hi! I'm not really sure what the question is? All this module does is print out the error you handed to it. It sounds like you simply wouldn't even call this module for errors. Can you demonstrate an example of what you mean or even a PR :)?

**Comment by ericuldall** [comment]
Yes. I wouldn't. unfortunately express uses this module. So i'm just looking into viable options for a fork.

**Comment by dougwilson** [comment]
Gotcha. I mean, perhaps you would want to file an issue with Express. Can you also perhaps explain specifically what "allow unhandled errors to bubble up?" means?

**Comment by ericuldall** [comment]
Perhaps you're right. This may be express catching thrown errors and passing them into finalhandler. I'm still digging through the code. This module was just to point of output so I started here.

**Comment by ericuldall** [comment]
Sorry. Bubble up means, don't catch my error for me.

**Comment by dougwilson** [comment]
Express only defaults to this module if you don't provide your app with a final callback. If you provide a callback, you can do anything you want:
```js
var app = express()
var http = require('http')

// declare things on app

var server = http.createServer(function (req, res) {
  app(req, res, function (err) {
    // this is your replacement for finalhandler
  })
})

server.listen(3000)
```

**Comment by ericuldall** [comment]
thank you :D
